<?php

use Illuminate\Support\Str;
use Spatie\ResponseCache\Facades\ResponseCache;

use function Pest\Laravel\get;

it('includes PWA manifest link and service worker registration on the storefront', function () {
    ResponseCache::clear();

    $response = get(route('shop.home.index'));

    $response->assertOk();

    $html = $response->content();

    expect(Str::contains($html, 'rel="manifest"'))->toBeTrue();
    expect(Str::contains($html, '/manifest.webmanifest'))->toBeTrue();
    expect(Str::contains($html, 'serviceWorker.register'))->toBeTrue();
    expect(Str::contains($html, 'name="theme-color"'))->toBeTrue();
});

it('serves manifest.webmanifest JSON when generated by the Shop build', function () {
    ResponseCache::clear();

    $response = get(route('shop.pwa.manifest'));

    $response->assertOk();

    $data = json_decode($response->getContent(), true);

    expect($data)->toBeArray()
        ->and($data)->toHaveKeys(['name', 'short_name', 'start_url', 'display', 'icons']);
})->skip(
    fn () => ! file_exists(public_path('manifest.webmanifest')),
    'Run npm run build in packages/Webkul/Shop to generate PWA assets.'
);
